version: '3.8'
services:
  adminservice:
    build:
      context: .
      dockerfile: src/Services/AdminService/Dockerfile
    ports:
      - "5000:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge